title: Xu Liyang's Homepage
page-top-title: Xu Liyang
top-section-bg-text: It is a far, far better thing that I do, than I have ever done
home-subtitle: Xu Liyang&ensp;|&ensp;
copyright-text: '&copy; Xu Liyang 2023-2025. All Rights Reserved.'